### ISSUE TITLE
Use flexbox for responsive layout

### ISSUE THREAD

**Issue by joyceerhl** [AdvisorySG/mentorship-page#13]
Is there a reason we're not using flexbox for styling our frontend? I think it might help with centering elements and ensuring things are generally aligned.

**Comment by wei2912** [comment]
Agreed, it'll help a lot if we made use of flexbox. A good tutorial is https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by wei2912** [comment]
Looks like we've done plenty of this, will be closing.
