### ISSUE TITLE
Modal does not stay in absolute position

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/mentorship-page#21]
![2020-04-12-151225_scrot](https://user-images.githubusercontent.com/2070423/79062847-386e0e80-7cd0-11ea-8610-a33d63571445.png)

When I scroll down, the modal remains at the top and does not maintain in its original position.

**Comment by joyceerhl** [comment]
Just to check, per #22 we're disallowing background scroll while the modal is active, yes?

**Comment by wei2912** [comment]
@joyceerhl Yes, that is right.

**Comment by wei2912** [comment]
Fixed already, thanks!
