### ISSUE TITLE
Dark overlay when modal is active

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/mentorship-page#22]
We should have a dark overlay over everything else so that when the modal pops up more, we can't press the "Read More" button of another card.

This should be done after https://github.com/AdvisorySG/mentorship-page/pull/16 is done with an additional change to close the modal by clicking outside of it.

**Comment by bnjmnt4n** [comment]
Maybe you might also want to restrict scrolling through the document as well?

**Comment by wei2912** [comment]
@bnjmnt4n That makes sense, thanks for specifying that additional requirement.
