### ISSUE TITLE
Height of profile pictures in profile cards is inconsistent

### ISSUE THREAD

**Issue by bnjmnt4n** [AdvisorySG/mentorship-page#32]
Here’s an example:

![Screen Shot 2020-04-15 at 8 03 12 PM](https://user-images.githubusercontent.com/813865/79335233-40d67b80-7f54-11ea-8999-8e65de35ac3d.png)

Is this a design feature or something we want to look at?

**Comment by wei2912** [comment]
Hmm, all the photos provided for the mentors will be square so it shouldn't
be a problem if the card width is fixed.

**Comment by wei2912** [comment]
The photos aren't actually square now, we gotta center everything and make sure they don't get squashed
