### ISSUE TITLE
[MPT-6] Use icons to display industry tags

### ISSUE THREAD

**Issue by faisalsgithub** [AdvisorySG/mentorship-page#330]
The current pills are not ideal, perhaps consider using icons, since there are 48 industries perhaps an icon for a "cluster" (set of industries)

<sub>[MPT-6](https://linear.app/advisorysg/issue/MPT-6/use-icons-to-display-industry-tags)</sub>

**Comment by Hackin7** [comment]
This issue is old and thus not really applicable to our new website.
I'll be marking it as stale first, but it can be reopened/ recreated if needed
