### ISSUE TITLE
[MPT-3] Content Redesign

### ISSUE THREAD

**Issue by amirulraziqi** [AdvisorySG/mentorship-page#350]
Redesign the non-mentor content, as seen below, to be more intuitive/iuser-friendly

![image](https://user-images.githubusercontent.com/66960654/133931313-81bea9d1-c9ea-46f7-b2af-f870b1dee844.png)

<sub>[MPT-3](https://linear.app/advisorysg/issue/MPT-3/content-redesign)</sub>

**Comment by florallam** [comment]
![header_mockup](https://user-images.githubusercontent.com/55974415/134688870-4d56511b-8bd3-4e46-be47-989bea29edea.png)

- Sample of the mockup done using Figma
- Suggested to get the buttons up + sticky headers there first
- Don't need to format the 'Apply Now' button, might need to standardise it

**Comment by Hackin7** [comment]
This issue is old and thus not really applicable to our new website.
I'll be marking it as stale first, but it can be reopened/ recreated if needed
