### ISSUE TITLE
Mentor Card Information Redesign

### ISSUE THREAD

**Issue by amirulraziqi** [AdvisorySG/mentorship-page#398]
Repurpose the text content in the mentor card to only show all mentor details - name, industries, organisation, role, full biography, course of study, school graduated from, thumbnail image

Not to do: 
    Resize card
    Change card layout

**Comment by IvanFengJK** [comment]
Started on it. Created a branch for it. Customised Result Display for mentorship card #405 Got it working except for the course of study part.

**Comment by wei2912** [comment]
Have been merged, closing.
