### ISSUE TITLE
Implement Material-UI Dropdown Functionality on Card Component

### ISSUE THREAD

**Issue by amirulraziqi** [AdvisorySG/mentorship-page#399]
To do:
    Implement either a card or accordion component in Material UI to showcase mentor bio
Not to do:    
    Modal functionality

**Comment by wei2912** [comment]
Please refer to the following:
1. https://github.com/AdvisorySG/mentorship-page/blob/0bc9f1f7db8fe5027dc7ee14f38c95888787c04e/src/components/profile-modal.tsx
2. https://github.com/AdvisorySG/mentorship-page/blob/0bc9f1f7db8fe5027dc7ee14f38c95888787c04e/src/App.tsx - take note of `ProfileModal`. Hash functionality (https://github.com/AdvisorySG/mentorship-page/blob/0bc9f1f7db8fe5027dc7ee14f38c95888787c04e/src/App.tsx#L42-L84) should be implemented after the modal is done.

**Comment by amirulraziqi** [comment]
> Please refer to the following:
> 
> 1. https://github.com/AdvisorySG/mentorship-page/blob/0bc9f1f7db8fe5027dc7ee14f38c95888787c04e/src/components/profile-modal.tsx
> 2. https://github.com/AdvisorySG/mentorship-page/blob/0bc9f1f7db8fe5027dc7ee14f38c95888787c04e/src/App.tsx - take note of `ProfileModal`. Hash functionality (https://github.com/AdvisorySG/mentorship-page/blob/0bc9f1f7db8fe5027dc7ee14f38c95888787c04e/src/App.tsx#L42-L84
>    ) should be implemented after the modal is done.

@wei2912 This is no longer relevant since this feature mentions material-ui dropdown as opposed to modal component, no?

**Comment by wei2912** [comment]
> @wei2912 This is no longer relevant since this feature mentions material-ui dropdown as opposed to modal component, no?

Yep it's not, since we decided to move on with a MUI collapsible.
