### ISSUE TITLE
[MPT-11] Search Query Relevance Tuning

### ISSUE THREAD

**Issue by amirulraziqi** [AdvisorySG/mentorship-page#401]
To do:
    Test out search query relevancy
    Propose an optimal way to tune search query field relevancy within elasticsearch, and tune the search query relevancy within elasticsearch accordingly

<sub>[MPT-11](https://linear.app/advisorysg/issue/MPT-11/search-query-relevance-tuning)</sub>

**Comment by wei2912** [comment]
Linked to https://github.com/AdvisorySG/mentorship-page/issues/499. Needs research to figure out what can be done.

**Comment by wei2912** [comment]
Closing since there's not much to be done for this currently...
