### ISSUE TITLE
Add industries into the mentor card

### ISSUE THREAD

**Issue by amirulraziqi** [AdvisorySG/mentorship-page#422]
Each of the mentor's industries is to be displayed in the mentor card, as a comma-separated list, above the role field.

**Comment by wei2912** [comment]
As of https://github.com/AdvisorySG/mentorship-page/commit/8ae2e9df83c50364fbb4858898e4606fdea02b10 this has been completed. @amirulraziqi do you think we should follow with your suggested UI changes to display the industries as pills, or should we reassign the tasks?

**Comment by amirulraziqi** [comment]
> As of [8ae2e9d](https://github.com/AdvisorySG/mentorship-page/commit/8ae2e9df83c50364fbb4858898e4606fdea02b10) this has been completed. @amirulraziqi do you think we should follow with your suggested UI changes to display the industries as pills, or should we reassign the tasks?

Sounds good. Will assign @IvanFengJK this in a new issue.
