### ISSUE TITLE
Display industries as pills

### ISSUE THREAD

**Issue by amirulraziqi** [AdvisorySG/mentorship-page#425]
Display all industries as pills. I imagine the industries pills will be displayed to the right of the mentor's name, as per the drawing below, but am open to suggestions.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/66960654/161393066-8b96bc00-6238-432d-be9f-176f55d70829.png">

You can take style reference from https://mentorcruise.com/filter/ProductManagement/. In particular, the pills can be styled as per boxed below:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/66960654/161393001-3eb2ce7e-365f-455e-984e-6c3fef76aa94.png">

**Comment by wei2912** [comment]
Consider using https://mui.com/components/chips/.

**Comment by wei2912** [comment]
Merged in https://github.com/AdvisorySG/mentorship-page/commit/ebd8c1f238b271011aaf6d6bd5a4cb75e5c03305, closing.
