### ISSUE TITLE
Some mentor info snippets missing closing brackets

### ISSUE THREAD

**Issue by amirulraziqi** [AdvisorySG/mentorship-page#440]
See Role and Course of Study in mentor card below to see the issue. Should have something to do with how the snippets are processed. 

<img width="516" alt="image" src="https://user-images.githubusercontent.com/66960654/163758076-1e8fe073-10b0-4294-a90f-2d6bf9561e74.png">

**Comment by wei2912** [comment]
This is some strange behaviour involving snippets and fallback. By right, if no part of the field is highlighted then the raw value should be returned (with truncation based on char limit). Unfortunately, the bracket gets truncated even though the raw field is fine:

"Sourabh" (no highlight in role):

![image](https://user-images.githubusercontent.com/2070423/163823432-5ad04114-edc7-4f94-a901-74e605d6f3bc.png)

"Sourabh pay" (highlight in role):

![image](https://user-images.githubusercontent.com/2070423/163823528-32f8f13c-006e-4bc1-8b79-26f877981f73.png)

Workaround would be to disable fallback and enable raw instead, then change the code so it checks for snippet and then raw.

**Comment by wei2912** [comment]
A hotfix has been applied at https://github.com/AdvisorySG/mentorship-page/commit/e21e5adb6d07c9433c10bd074038048b94f217c9, which adds back the missing brackets.
