### ISSUE TITLE
Mentor image thumbnail not consistent when Read More button is pressed

### ISSUE THREAD

**Issue by amirulraziqi** [AdvisorySG/mentorship-page#464]
Mentor image thumbnail scales alongside fullbio when Read More button is pressed. Goal is to keep the image size consistent.

Before:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/66960654/166209148-b76f95c3-2bdb-452b-bcd8-0fa0be402f3a.png">

After:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/66960654/166209179-74d75f46-bf7f-47f9-8393-927f32ef7b4d.png">

**Comment by wei2912** [comment]
Fixed in https://github.com/AdvisorySG/mentorship-page/commit/9a108c72d473e3b3f1ddba6e57dd85a3a0977ecf.
