### ISSUE TITLE
Implement toggle between card grid view and horizontal view

### ISSUE THREAD

**Issue by amirulraziqi** [AdvisorySG/mentorship-page#468]
Currently, the [mentorship website](mentorship.advisory.sg) displays the mentor cards in a horizontal view. However, users should have the ability to toggle between a new grid view and the exisitng horizontal view.

Grid view will be the new default viewing style. In grid view, there will be 3 mentor cards per row. Each mentor card will display the mentor thumbnail, name, current role, and current organization, and will be styled similar to the [mentorship2020 website](mentorship2020.advisory.sg). A read more button will also be present that when clicked, will open up a modal containing the mentor card in horizontal view. 

Both display views will fix number of mentors displayed at 40.

Also, we can do away with the pagination number selection 
<img width="105" alt="image" src="https://user-images.githubusercontent.com/66960654/169689707-c6fad1d6-79aa-4c0e-ba83-fd138aaa616a.png">
and instead use that space for the toggle button

**Comment by wei2912** [comment]
Has been merged, closing.
