### ISSUE TITLE
[MPT-16] Switching tabs is not reflected in query parameters

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/mentorship-page#521]
Tab switches are not reflected under query parameters. This means that a user copy pasting a link and sending to another person may get inconsistent results, even though the current page is reflected in the query parameters, as the current tab may not be aligned.

<sub>[MPT-16](https://linear.app/advisorysg/issue/MPT-16/switching-tabs-is-not-reflected-in-query-parameters)</sub>

**Comment by wei2912** [comment]
Try putting tab ID at the base, e.g. `/mentors/0?n_size=...` where 0 is tab ID.

**Comment by Hackin7** [comment]
https://github.com/AdvisorySG/mentorship-page/pull/633 Merged in
