### ISSUE TITLE
[MPT-15] Navigation bar

### ISSUE THREAD

**Issue by jcc-kh** [AdvisorySG/mentorship-page#574]
4 "sub-pages" are needed for the new website:
 
1. About Us (links to the main Advisory page)
2. Mentorship Program
3. FAQ
4. Application

<sub>[MPT-15](https://linear.app/advisorysg/issue/MPT-15/navigation-bar)</sub>

**Comment by wei2912** [comment]
Please refer to these new links:

1. Advisory (placeholder link, externally directs to advisory.sg; TBC if replace by logo)
2. Find A Mentor
3. FAQ
4. Apply Now

Placeholder text can be set for these links. Design should ideally be similar to https://beta.advisory.sg/, get in touch with @Hackin7/@soloplxya on how to copy over the design code from https://github.com/AdvisorySG/dawn-advisory-theme!

![image](https://user-images.githubusercontent.com/2070423/224490999-61e759f3-be37-4d35-9471-60cc6d08a387.png)
