### ISSUE TITLE
[MPT-43] No home button

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/mentorship-page#643]
There is no way for a person to navigate to mentorship.advisory.sg based on the current navigation bar:

![image](https://github.com/AdvisorySG/mentorship-page/assets/2070423/ea182773-f039-487b-b148-40031cea260f)

The PR should be targeted towards `multi-page` branch.

**Comment by wei2912** [comment]
To create a new link in the navigation bar called "Home".

**Comment by jeffzy15** [comment]
I have created a pull request (#647).
