### ISSUE TITLE
[MPT-44] Mentors: Search result highlighting is displayed as italics

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/mentorship-page#644]
![image](https://github.com/AdvisorySG/mentorship-page/assets/2070423/25561b80-1882-4e0e-99be-383f35c5afcf)

This is likely an issue with the way past CSS is being applied to the new mentors components.

**Comment by wei2912** [comment]
Instead of italics, the matching queries should be highlighted as in here:

![image](https://github.com/AdvisorySG/mentorship-page/assets/2070423/79cb61d5-6ab9-4710-ae68-6875e71de7b6)

I think this issue only applies to the name, but do confirm that this is the case.

**Comment by jeffzy15** [comment]
I've created a PR (#653)

**Comment by wei2912** [comment]
Closing, addressed in https://github.com/AdvisorySG/mentorship-page/pull/653.
