### ISSUE TITLE
Styling improvements for search bar

### ISSUE THREAD

**Issue by RyanRTJJ** [AdvisorySG/mentorship-page#68]
Some suggestions for styling of the search bar and intro paragraph. Not too impt. Could be done anytime.

1) Can we increase the margin / padding top of the search bar? Visually associate it with the cards section and distance it a bit from the header.

2) Can we decrease the search bar's height so that it looks a little sleeker? Now it's about 300% of the text size, maybe about 200% would be good? The font-sizes of everything in the search bar (including suggestions) could also be at 90% (to match with the cards)?

3) Also for the introductory paragraph itself can we have `text-align: justify center` instead of just `justify`?

**Comment by wei2912** [comment]
@RyanRTJJ Uhh, what was your intended result when you wrote `text-align: justify center`? :P That's not a valid option if you see [the syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align).

**Comment by wei2912** [comment]
I've addressed 1 and 2 for the search bar, please see the latest PR.

**Comment by amirulraziqi** [comment]
Search bar UI will be enhanced in upcoming search feature update
