### ISSUE TITLE
[MPT-63] Adding call to action to apply to homepage

### ISSUE THREAD

**Issue by jcc-kh** [AdvisorySG/mentorship-page#708]

**Comment by w3joe** [comment]
@jcc-kh Here's a draft for the call to action, to be placed below the "testimonials" section on homepage for desktop:

<img width="675" alt="image" src="https://github.com/AdvisorySG/mentorship-page/assets/84664178/22ab4e21-0408-4fb0-8232-ad9acba1ed0a">

I would need some advice for the paragraph text, and do let me know if this is what you had in mind.

**Comment by w3joe** [comment]
Mobile:
<img width="376" alt="image" src="https://github.com/AdvisorySG/mentorship-page/assets/84664178/022bf7f7-3ad6-42f2-8195-ef11876fa53b">

Desktop:
<img width="876" alt="image" src="https://github.com/AdvisorySG/mentorship-page/assets/84664178/859f4286-1103-4af3-b892-70fef7e4caa7">

**Comment by wei2912** [comment]
Closed in https://github.com/AdvisorySG/mentorship-page/commit/4a94fc9173f4b7032891b21e6d3910d0a83eebb2.
