### ISSUE TITLE
Mentors: Remove of category label for mentors profile

### ISSUE THREAD

**Issue by jcc-kh** [AdvisorySG/mentorship-page#769]
![image](https://github.com/AdvisorySG/mentorship-page/assets/115876276/6a1b332e-0680-4b0c-b419-eb73b150f833)

If there isn't available information then do not show the category label (i.e instead of _studied no info_, just remove the label altogether)

**Comment by wei2912** [comment]
Closing; see https://github.com/AdvisorySG/mentorship-page/pull/795#issuecomment-2212367704.
